// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package jobInfo

import (
	"database/sql"
	"time"
)

type JobInfo struct {
	ID             int64
	CreatedTime    time.Time
	JobName        string
	Company        string
	JobDescription sql.NullString
	JobType        sql.NullString
	JobCategory    sql.NullString
	JobLocation    sql.NullString
	IsChecked      bool
	IsExists       bool
}
